### ISSUE TITLE
1.19 purpur server AdvancedReplay console error 

### ISSUE THREAD

**Issue by T4B999** [Jumper251/AdvancedReplay#101]
[11:24:58 ERROR]: [AdvancedReplay] Unhandled exception number 1024 occurred in onPacketSending(PacketEvent) for AdvancedReplay
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 6, Size: 5)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.packetwrapper.WrapperPlayServerSpawnEntity.getType(WrapperPlayServerSpawnEntity.java:322) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.recording.PacketRecorder$1.onPacketSending(PacketRecorder.java:169) ~[Replay.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:274) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:259) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2393) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2306) ~[?:?]
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:2041) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:1203) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2643) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2580) ~[?:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.startTracking(PersistentEntitySectionManager.java:227) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:187) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntity(PersistentEntitySectionManager.java:166) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1530) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1433) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:296) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:213) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:183) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1035) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:911) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:668) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1579) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Using this ProtocolLib version  - https://ci.dmulloy2.net/job/ProtocolLib/569/

**Comment by Jumper251** [comment]
1.19 is now supported.
