### ISSUE TITLE
Bug in console looks like Mysql communication issues Java JDK 18

### ISSUE THREAD

**Issue by lorentedford** [Jumper251/AdvancedReplay#107]
Here is what I am seeing in console.. Server 1.19.1 spigot. Java jdk 18

`[AdvancedReplay]: Plugin AdvancedReplay v1.8.2 generated an exception while executing task 16
Console16:18:13
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null
at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:79) ~[?:?]
at me.jumper251.replay.database.utils.AutoReconnector.run(AutoReconnector.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Server thread/INFO16:19:00
Current Memory Usage: 982/2576 mb (Max: 8192 mb)
Craft Scheduler Thread - 4/WARN16:19:13
[AdvancedReplay]: Plugin AdvancedReplay v1.8.2 generated an exception while executing task 16
Console16:19:13
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null
at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:79) ~[?:?]
at me.jumper251.replay.database.utils.AutoReconnector.run(AutoReconnector.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Jumper251** [comment]
Are there any error messages on startup?
