### ISSUE TITLE
ConcurrentModificationException: null

### ISSUE THREAD

**Issue by modcrafts** [Jumper251/AdvancedReplay#108]
When recording players, this error always occured
Using `Dionysus 1.12.2` `AdvancedReplay v1.8.2`
```
[23:35:26] [Craft Scheduler Thread - 281/WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.8.2 generated an exception while executing task 937502
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1617) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1615) ~[?:?]
	at java.util.HashMap.putMapEntries(HashMap.java:513) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at me.jumper251.replay.replaysystem.recording.Recorder$1.run(Recorder.java:83) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[23:35:30] [Craft Scheduler Thread - 281/WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.8.2 generated an exception while executing task 937502
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1598) ~[?:?]
	at java.util.AbstractSet.removeAll(AbstractSet.java:176) ~[?:?]
	at me.jumper251.replay.replaysystem.recording.Recorder$1.run(Recorder.java:107) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```
plugin list
```
Plugins (27): AdminAnything (2.4.12), AdvancedAntiXray (1.5.2), AdvancedReplay (1.8.2), AntiCheatReplay (2.7.4), 
AureliumSkills (Beta 1.2.10), AuthMe (5.6.0-SNAPSHOT-b2509), AzLink (1.1.1), CMI (9.1.4.1), CMILib (1.2.3.3), GrimAC (2.3.23), 
InventoryRollbackPlus (1.6.7), Kingdoms (1.14.2.0.0.1-BETA), LiteBans (2.10.3), LuckPerms (5.4.5), PlaceholderAPI (2.11.2), Plan (5.5 build 1791), 
ProtocolLib (5.0.0-SNAPSHOT-b591), ServerListPlus (3.4.8), ServerUtils (3.5.2), SimpleCombatTag (1.1), SkinsRestorer (14.2.3), 
StarMail (1.7.2), TAB (3.1.4), Vault (1.7.3-b131), WorldEdit (6.1.7;dd00bb1), WorldGuard (6.2.2-SNAPSHOT;8eeab68) and XConomy (2.16.1)
```

**Comment by ChanceSD** [comment]
Same thing here, was about to create a report

```[22:34:57 WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.8.2 generated an exception while executing task 2975433
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at java.util.HashMap.putMapEntries(HashMap.java:511) ~[?:?]
        at java.util.HashMap.<init>(HashMap.java:484) ~[?:?]
        at me.jumper251.replay.replaysystem.recording.Recorder$1.run(Recorder.java:83) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Tuinity-"5b4d7a7"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Tuinity-"5b4d7a7"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Tuinity-"5b4d7a7"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

**Comment by Jumper251** [comment]
This bug is difficult to reproduce, but I have made some changes that will hopefully fix it. 
If the bug still exists just reopen this issue or create a new one.
