### ISSUE TITLE
Error when attempting to exit replay

### ISSUE THREAD

**Issue by ChiboYen** [Jumper251/AdvancedReplay#118]
```
[03:06:26 ERROR]: Could not pass event PlayerQuitEvent to AdvancedReplay v1.8.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitRunnable.cancel()" because "this.run" is null
        at me.jumper251.replay.replaysystem.replaying.Replayer.stop(Replayer.java:179) ~[Replay.jar:?]
        at me.jumper251.replay.listener.ReplayListener.onQuit(ReplayListener.java:189) ~[Replay.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor159.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1876]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:575) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:558) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2210) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2189) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:786) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Jumper251** [comment]
Closed #121
