### ISSUE TITLE
MySQL: No suitable driver found

### ISSUE THREAD

**Issue by dchu096** [Jumper251/AdvancedReplay#125]
On starting the server and looking into logs, here is what i have found.

```
[04:40:26] [Server thread/INFO]: [AdvancedReplay] Enabling AdvancedReplay v1.8.3*
--
521 | [04:40:26] [Server thread/INFO]: [AdvancedReplay] Loading Replay v1.8.3 by Jumper251
522 | [04:40:26] [Server thread/INFO]: [AdvancedReplay] Unable to connect to MySQL database: No suitable driver found for jdbc:mysql://**.**.**.**:3306/eco_replay?useSSL=false&characterEncoding=latin1
523 | [04:40:26] [Server thread/ERROR]: Error occurred while enabling AdvancedReplay v1.8.3 (Is it up to date?)
524 | java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "this.connection" is null
525 | at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:79) ~[Replay.jar:?]
526 | at me.jumper251.replay.database.MySQLService.createReplayTable(MySQLService.java:30) ~[Replay.jar:?]
527 | at me.jumper251.replay.filesystem.ConfigManager.loadData(ConfigManager.java:131) ~[Replay.jar:?]
528 | at me.jumper251.replay.filesystem.ConfigManager.loadConfigs(ConfigManager.java:91) ~[Replay.jar:?]
529 | at me.jumper251.replay.ReplaySystem.onEnable(ReplaySystem.java:52) ~[Replay.jar:?]
530 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
531 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
532 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
533 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-381]
534 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-381]
535 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-381]
536 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-381]
537 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-381]
538 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-381]
539 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-381]
540 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
541 | [04:40:26] [Server thread/INFO]: [AdvancedReplay] Disabling AdvancedReplay v1.8.3
```

**Comment by dchu096** [comment]
Sorry if this is a duplicate of #107
