### ISSUE TITLE
Field index 0 is out of bounds for length 0

### ISSUE THREAD

**Issue by NockyCZ** [Jumper251/AdvancedReplay#145]
Hi, i can play replay.  But I can't control it in any way
ProtocolLib 5.0.0, Paper 1.19.2
```
[12:35:48 WARN]: [AdvancedReplay] Task #61 for AdvancedReplay v1.8.4 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
at com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.setAction(WrapperPlayServerPlayerInfo.java:51) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.getInfoAddPacket(PacketNPC.java:295) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.spawn(PacketNPC.java:93) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.spawnNPC(ReplayingUtils.java:474) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:85) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:144) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.replaying.Replayer.start(Replayer.java:101) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:69) ~[Replay.jar:?]
at me.jumper251.replay.replaysystem.Replay.lambda$play$0(Replay.java:60) ~[Replay.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NockyCZ** [comment]
And when i leave leave server

```
[12:41:22 INFO]: Nockys lost connection: Disconnected
[12:41:22 ERROR]: Could not pass event PlayerQuitEvent to AdvancedReplay v1.8.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitRunnable.cancel()" because "this.run" is null
at me.jumper251.replay.replaysystem.replaying.Replayer.stop(Replayer.java:179) ~[Replay.jar:?]
at me.jumper251.replay.listener.ReplayListener.onQuit(ReplayListener.java:189) ~[Replay.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor61.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:627) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:612) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2127) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2107) ~[?:?]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:778) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by NockyCZ** [comment]
Oh i see, plugin doesnt work on 1.19.2
