### ISSUE TITLE
Replays not viewable in 1.20.2

### ISSUE THREAD

**Issue by Budderman18** [Jumper251/AdvancedReplay#151]
Replays can be made but not viewed. Players also are stuck inside them with no way to leave until the server restarts

[AdvancedReplay] Task #3636793 for AdvancedReplay v1.8.4 generated an exception
java.lang.IllegalArgumentException: Could not find packet for type NAMED_ENTITY_SPAWN
        at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$1(PacketRegistry.java:426) ~[ProtocolLib.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:426) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at com.comphenix.packetwrapper.WrapperPlayServerNamedEntitySpawn.<init>(WrapperPlayServerNamedEntitySpawn.java:41) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.<init>(PacketNPC.java:68) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.spawnNPC(ReplayingUtils.java:446) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:85) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:144) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.start(Replayer.java:101) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:69) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.lambda$play$0(Replay.java:60) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1472) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1381) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1158) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[pufferfish-1.20.2.jar:git-Pufferfish-28]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by TheKrafter** [comment]
Experiencing this exact same issue.

**Comment by TheKrafter** [comment]
Also, @Budderman18 could you wrap your logs in `<details>` or something? or use a paste service please?

**Comment by Budderman18** [comment]
> Experiencing this exact same issue.

Please dont send stuff like that unless you’re adding information. Doesn’t help anyone and tricks people into thinking they got a response from support or something.

**Comment by Budderman18** [comment]
> Also, @Budderman18 could you wrap your logs in `<details>` or something? or use a paste service please?

I didn’t send any logs. If you’re counting the stack trace as a log, its short enough to not need one.

**Comment by Jumper251** [comment]
The latest update should fix the issues with 1.20.2
