### ISSUE TITLE
EntityToggleSwimEvent error

### ISSUE THREAD

**Issue by bobhenl** [Jumper251/AdvancedReplay#162]
```
[09:16:12] [Server thread/ERROR]: Could not pass event EntityToggleSwimEvent to AdvancedReplay v1.8.5
java.lang.NullPointerException: Cannot invoke "me.jumper251.replay.replaysystem.recording.PlayerWatcher.setSwimming(boolean)" because "watcher" is null
	at me.jumper251.replay.replaysystem.recording.CompListener.onSwim(CompListener.java:75) ~[Replay.jar:?]
	at me.jumper251.replay.utils.ReflectionHelper.lambda$registerEvent$0(ReflectionHelper.java:113) ~[Replay.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2165]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callToggleSwimEvent(CraftEventFactory.java:1832) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.world.entity.Entity.setSwimming(Entity.java:3364) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.world.entity.Entity.updateSwimming(Entity.java:1891) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.world.entity.player.Player.updateSwimming(Player.java:1731) ~[?:?]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:888) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:412) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:852) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3116) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:303) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:352) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1781) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2165]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

spamming the console regualrly

**Comment by Jumper251** [comment]
There were some updates, please check if the latest version still has this error.
