### ISSUE TITLE
replays not working on 1.20.5/6 or 1.21

### ISSUE THREAD

**Issue by Budderman18** [Jumper251/AdvancedReplay#164]
this stack trace (or similar) appear when either creating, opening, or leaving a replay (this one is specifically for starting)

 Command exception: /replay start amongus
org.bukkit.command.CommandException: Unhandled exception executing command 'replay' in plugin AdvancedReplay v1.8.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:git-Paper-71]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1517) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1494) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1417) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1609) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-71]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant me.jumper251.replay.utils.VersionUtil.VersionEnum.CRAFTBUK
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:54) ~[paper-1.20.6.jar:git-Paper-71]
        at Replay.jar/me.jumper251.replay.utils.VersionUtil$VersionEnum.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(VersionUtil.java) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.utils.VersionUtil$VersionEnum.valueOf(VersionUtil.java:56) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.utils.VersionUtil.isBelow(VersionUtil.java:31) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.replaysystem.recording.PacketRecorder.register(PacketRecorder.java:101) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.replaysystem.recording.Recorder.start(Recorder.java:69) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.replaysystem.Replay.recordAll(Replay.java:51) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.api.ReplayAPI.recordReplay(ReplayAPI.java:55) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.commands.replay.ReplayStartCommand.execute(ReplayStartCommand.java:60) ~[Replay.jar:?]
        at Replay.jar/me.jumper251.replay.commands.AbstractCommand.onCommand(AbstractCommand.java:73) ~[Replay.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more

**Comment by Jumper251** [comment]
1.21 is now supported.
