### ISSUE TITLE
The plugin does not work correctly

### ISSUE THREAD

**Issue by Derim16** [Jumper251/AdvancedReplay#169]
Hello. How to fix it?
https://paste.helpch.at/mujupirosi.rb

**Comment by Jumper251** [comment]
Looks like this error message might be caused by another error.
Were there any other errors before this one?

**Comment by Derim16** [comment]
No. It happens specifically when trying to view a replay or do anything else with it within the game.

**Comment by Jumper251** [comment]
Did you get any errors while recording the replay?
Do parts of the replay work, are there some players in it that move or is nothing working?

It could also help if you would send me the replay file from the error message.

**Comment by mordisk10** [comment]
i can also confirm that this happens only with the latest version (1.8.6) and 
latest version (5.2.0) of ProtocolLib

when i changed the AdvancedReplay to 1.8.5 it started working again

> Do parts of the replay work

yes recording **seems** to be working.

> are there some players in it that move or is nothing working?

when you play the replay, there are no players, plugin cannot create any npcs.

**Comment by Jumper251** [comment]
You have to use the latest dev build (ProtocolLib 5.3.0) for AdvancedReplay version 1.8.6.

**Comment by Derim16** [comment]
[01:57:56 WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.8.6 generated an exception while executing task 6291
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.wrappers.WrappedDataWatcher$Serializer.getHandle()" because "serializer" is null
        at com.comphenix.protocol.wrappers.WrappedDataValue.newHandle(WrappedDataValue.java:65) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataValue.<init>(WrappedDataValue.java:47) ~[ProtocolLib.jar:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.lambda$updateMetadata$0(PacketNPC.java:233) ~[Replay.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.updateMetadata(PacketNPC.java:231) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:192) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:144) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer$1.run(Replayer.java:115) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Jumper251** [comment]
What version of ProtocolLib do you use?

**Comment by Derim16** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/

Latest.

**Comment by Jumper251** [comment]
[80c5b91](https://github.com/Jumper251/AdvancedReplay/commit/80c5b912f4980a811b1da3a0ce75d4dfeff441cc) (https://github.com/Jumper251/AdvancedReplay/actions/runs/9696028077) fixes a bug in 1.20.6, maybe this also fixes your issue in 1.20.4.

**Comment by Derim16** [comment]
It was corrected by what you posted 4 days ago. 
https://paste.helpch.at/kamizopeva.rb
