### ISSUE TITLE
A error in console and sometimes the server crashes because of it

### ISSUE THREAD

**Issue by HEMO313** [Jumper251/AdvancedReplay#172]
[10:56:30 ERROR]: [AdvancedReplay] Unhandled exception occurred in onPacketSending(PacketEvent) for AdvancedReplay
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247) ~[ProtocolLib.jar:?]
        at com.comphenix.packetwrapper.WrapperPlayServerExplosion.getSound(WrapperPlayServerExplosion.java:266) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.data.types.ExplosionData.fromPacket(ExplosionData.java:174) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.recording.PacketRecorder$1.onPacketSending(PacketRecorder.java:140) ~[Replay.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.b(Connection.java) ~[?:?]
        at net.minecraft.network.Connection.a(Connection.java) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.b(ServerCommonPacketListenerImpl.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.level.ServerLevel.a(ServerLevel.java) ~[?:?]
        at net.minecraft.world.level.Level.a(Level.java) ~[?:?]
        at net.minecraft.world.entity.boss.enderdragon.EndCrystal.a(EndCrystal.java) ~[?:?]
        at net.minecraft.world.entity.player.Player.d(Player.java) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.d(ServerPlayer.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.a(ServerboundInteractPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.a(ServerboundInteractPacket.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.a(ServerboundInteractPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.a(ServerboundInteractPacket.java) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:56:30 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutExplosion@6ecc4f87[
    a=-1003.5
    b=-24.0
    c=-956.5
    d=6.0
    e=[]
    f=0.0
    g=0.0
    h=0.0
    i=net.minecraft.core.particles.ParticleType@47fc680b
    j=net.minecraft.core.particles.ParticleType@337e55c2
    k=DESTROY_WITH_DECAY
    l=net.minecraft.sounds.SoundEffect@361f3c4
  ]

**Comment by Jumper251** [comment]
What version of ProtocolLib do you use?
What are the steps to reproduce this error?

**Comment by HEMO313** [comment]
protocollib latest
idk really it shows in console for no reason maybe when saving a replay i use anticheatreplay

**Comment by Jumper251** [comment]
You have to use the latest ProtocolLib [dev build](https://ci.dmulloy2.net/job/ProtocolLib/) (ProtocolLib 5.3.0)

**Comment by HEMO313** [comment]
> You have to use the latest ProtocolLib [dev build](https://ci.dmulloy2.net/job/ProtocolLib/) (ProtocolLib 5.3.0)

yeah i'm using latest dev build

**Comment by Jumper251** [comment]
Might be a problem with 1.20.4, AdvancedReplay usually only supports the latest version from a Minecraft update. If you get this error on 1.20.6 or 1.21, please upload another error message.

**Comment by HEMO313** [comment]
> Might be a problem with 1.20.4, AdvancedReplay usually only supports the latest version from a Minecraft update. If you get this error on 1.20.6 or 1.21, please upload another error message.

why tf does the plugin say it supports all versions from 1.8 - 1.21

**Comment by Jumper251** [comment]
If there are breaking protocol changes between minor versions I usually update the plugin to support the latest one. It does not happen on every version, but sometimes it will.
