### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by bobhenl** [Jumper251/AdvancedReplay#181]
Hello, I got this error in console on version 1.21 with the latest AdvancedReplay
```yml
21:26:38] [Server thread/ERROR]: Could not pass event nV to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: FIRE isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.data.types.SerializableItemStack.fromMaterial(SerializableItemStack.java:99) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:363) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:370) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.onBreak(RecordingListener.java:323) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2276.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.nj.a(SourceFile:97) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.cI.f(SourceFile:275) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1863) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:26:38] [Server thread/ERROR]: Could not pass event nV to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: FIRE isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.data.types.SerializableItemStack.fromMaterial(SerializableItemStack.java:99) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:363) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:370) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.onBreak(RecordingListener.java:323) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2276.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.nj.a(SourceFile:97) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at ItemsAdder_4.0.2-alpha-test-3.jar/ia.m.cI.f(SourceFile:275) ~[ItemsAdder_4.0.2-alpha-test-3.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1863) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Head-BOB** [comment]
same issue here
https://mclo.gs/J7W8WLv

**Comment by bobhenl** [comment]
```yml
18:26:46] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: PLAYER_WALL_HEAD isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.data.types.SerializableItemStack.fromMaterial(SerializableItemStack.java:99) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:363) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.recordBlockBreak(RecordingListener.java:370) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.onBreak(RecordingListener.java:323) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2266.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1863) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
there's more of them I guess

**Comment by bobhenl** [comment]
```yml
[02:54:35] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: POTATOES isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.data.types.SerializableItemStack.fromMaterial(SerializableItemStack.java:99) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.onPlace(RecordingListener.java:306) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:453) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:609) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1949) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2275-82ccc76]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by bobhenl** [comment]
List of items I noticed:
java.lang.IllegalArgumentException: MELON_STEM isn't an item
java.lang.IllegalArgumentException: ATTACHED_MELON_STEM isn't an item
java.lang.IllegalArgumentException: WALL_TORCH isn't an item
java.lang.IllegalArgumentException: POTATOES isn't an item
java.lang.IllegalArgumentException: PLAYER_WALL_HEAD isn't an item
java.lang.IllegalArgumentException: FIRE isn't an item
java.lang.IllegalArgumentException: REDSTONE_WIRE isn't an item
java.lang.IllegalArgumentException: COCOA isn't an item
java.lang.IllegalArgumentException: OAK_WALL_SIGN isn't an item
java.lang.IllegalArgumentException: ATTACHED_PUMPKIN_STEM isn't an item
java.lang.IllegalArgumentException: ACACIA_WALL_SIGN isn't an item
java.lang.IllegalArgumentException: WATER isn't an item
java.lang.IllegalArgumentException: CARROTS isn't an item
java.lang.IllegalArgumentException: POWDER_SNOW isn't an item
java.lang.IllegalArgumentException: SWEET_BERRY_BUSH isn't an item
java.lang.IllegalArgumentException: FROSTED_ICE isn't an item
java.lang.IllegalArgumentException: KELP_PLANT isn't an item
java.lang.IllegalArgumentException: SPRUCE_WALL_SIGN isn't an item
java.lang.IllegalArgumentException: CAVE_VINES isn't an item
java.lang.IllegalArgumentException: CAVE_VINES_PLANT isn't an item
java.lang.IllegalArgumentException: PISTON_HEAD isn't an item
java.lang.IllegalArgumentException: POTTED_DEAD_BUSH isn't an item
java.lang.IllegalArgumentException: TALL_SEAGRASS isn't an item
java.lang.IllegalArgumentException: DARK_OAK_WALL_SIGN isn't an item
java.lang.IllegalArgumentException: REDSTONE_WALL_TORCH isn't an item
java.lang.IllegalArgumentException: SOUL_FIRE isn't an item
java.lang.IllegalArgumentException: PUMPKIN_STEM isn't an item
java.lang.IllegalArgumentException: TRIPWIRE isn't an item
java.lang.IllegalArgumentException: BEETROOTS isn't an item
java.lang.IllegalArgumentException: POTTED_POPPY isn't an item
java.lang.IllegalArgumentException: WHITE_WALL_BANNER isn't an item
java.lang.IllegalArgumentException: WEEPING_VINES_PLANT isn't an item
java.lang.IllegalArgumentException: LIGHT_GRAY_WALL_BANNER isn't an item
java.lang.IllegalArgumentException: TWISTING_VINES_PLANT isn't an item



Note that there may be similar items: all sign types (even hanging ones), various farming items, wall items, plants, potted items, banners, etc.

**Comment by Jumper251** [comment]
There are some weird things going on with legacy material support and I have to update the plugin to a newer api version soon. For now [bdb2aab](https://github.com/Jumper251/AdvancedReplay/commit/bdb2aab5be705b64fc43a5bb8173a4f07d1c8f8e) (https://github.com/Jumper251/AdvancedReplay/actions/runs/10487872812) should fix this issue.

**Comment by VincentX0905** [comment]
**BlockPlaceEvent** & **BlockBreakEvent** error
```sh
[00:14:18 ERROR]: Could not pass event BlockPlaceEvent to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: WALL_TORCH isn't an item
```

```sh
[00:14:18 ERROR]: Could not pass event BlockBreakEvent to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: FIRE isn't an item
```

**Comment by Jumper251** [comment]
Please update the plugin to the latest version.
