### ISSUE TITLE
Could not pass event BlockPlaceEvent to AdvancedReplay v1.8.7

### ISSUE THREAD

**Issue by fadfhkdfga** [Jumper251/AdvancedReplay#182]
Could not pass event BlockPlaceEvent to AdvancedReplay v1.8.7
java.lang.IllegalArgumentException: REDSTONE_WIRE isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Replay-1.8.7.jar/me.jumper251.replay.replaysystem.data.types.SerializableItemStack.fromMaterial(SerializableItemStack.java:99) ~[Replay-1.8.7.jar:?]
        at Replay-1.8.7.jar/me.jumper251.replay.replaysystem.recording.RecordingListener.onPlace(RecordingListener.java:306) ~[Replay-1.8.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor268.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-13-7c9240f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:457) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:604) ~[paper-1.21.1.jar:1.21.1-13-7c9240f]

**Comment by Jumper251** [comment]
See #181
