### ISSUE TITLE
NoSuchMethodError on ProtocolLib

### ISSUE THREAD

**Issue by Lory9098** [Jumper251/AdvancedReplay#187]
Latest version of AdvancedReplay, Latest version of ProtocolLib.
[18:48:53 WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.8.9 generated an exception while executing task 1260
java.lang.NoSuchMethodError: 'void com.comphenix.protocol.wrappers.WrappedDataWatcher.setByte(int, byte, boolean)'
        at me.jumper251.replay.replaysystem.utils.MetadataBuilder.setByte(MetadataBuilder.java:36) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.utils.MetadataBuilder.resetValue(MetadataBuilder.java:60) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.recording.PlayerWatcher.getMetadata(PlayerWatcher.java:65) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:143) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:143) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer$1.run(Replayer.java:114) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-398]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-398]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

it happends randomly tbh

**Comment by Jumper251** [comment]
AdvancedReplay does not work well on 1.20.4, this error message should dissapear once you update to 1.21.
