### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedReplay v1.8.9

### ISSUE THREAD

**Issue by JanReich** [Jumper251/AdvancedReplay#189]
When viewing a replay (Mc/Server-Version 1.21.1) and clicking at the compass and than at the player at I am getting this exception:

[19:53:18 ERROR]: Could not pass event InventoryClickEvent to AdvancedReplay v1.8.9
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.Material.getId(Material.java:4748) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at Replay.jar/me.jumper251.replay.listener.ReplayListener.onClick(ReplayListener.java:143) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-62-5a503d7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-62-5a503d7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-62-5a503d7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[paper-1.21.jar:1.21-62-5a503d7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Jumper251** [comment]
Should be fixed by b103cfc (https://github.com/Jumper251/AdvancedReplay/actions/runs/10966283416)
