### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by bobhenl** [Jumper251/AdvancedReplay#197]
Hello, I'm getting this error:
```yml
18:50:06] [Server thread/ERROR]: [AdvancedReplay] Unhandled exception occurred in onPacketSending(PacketEvent) for AdvancedReplay
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at ProtocolLib.jar/com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247) ~[ProtocolLib.jar:?]
	at Replay.jar/me.jumper251.replay.libs.com.comphenix.packetwrapper.WrapperPlayServerExplosion.<init>(WrapperPlayServerExplosion.java:39) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.data.types.ExplosionData.fromPacket(ExplosionData.java:154) ~[Replay.jar:?]
	at Replay.jar/me.jumper251.replay.replaysystem.recording.PacketRecorder$1.onPacketSending(PacketRecorder.java:141) ~[Replay.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:497) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.Connection.send(Connection.java:457) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:347) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:328) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1879) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.Level.explode(Level.java:1528) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.Level.explode(Level.java:1523) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.boss.enderdragon.EndCrystal.hurt(EndCrystal.java:202) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at pvpclub-FasterCrystals-1.8.2.jar/xyz.reknown.fastercrystals.ver.damager.CrystalDamager_1_21_R1.damage(CrystalDamager_1_21_R1.java:33) ~[pvpclub-FasterCrystals-1.8.2.jar:?]
	at pvpclub-FasterCrystals-1.8.2.jar/xyz.reknown.fastercrystals.listeners.packet.AnimationListener.lambda$onPacketPlayReceive$1(AnimationListener.java:105) ~[pvpclub-FasterCrystals-1.8.2.jar:?]
	at pvpclub-FasterCrystals-1.8.2.jar/xyz.reknown.fastercrystals.packetevents.impl.util.folia.EntityScheduler.lambda$run$0(EntityScheduler.java:80) ~[pvpclub-FasterCrystals-1.8.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1770) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:50:06] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundExplodePacket@6457ae81[
    x=-653.5
    y=128.0
    z=-91.5
    power=6.0
    toBlow=[]
    knockbackX=-0.015907517
    knockbackY=0.08297184
    knockbackZ=-0.35408306
    smallExplosionParticles=net.minecraft.core.particles.SimpleParticleType@7f18aaf9
    largeExplosionParticles=net.minecraft.core.particles.SimpleParticleType@3d9cf35c
    blockInteraction=DESTROY_WITH_DECAY
    explosionSound=Reference{ResourceKey[minecraft:sound_event / minecraft:entity.generic.explode]=net.minecraft.sounds.SoundEvent@563e5f4f}
  ]
```

and sever is crashing, can this lead to crash?

**Comment by Jumper251** [comment]
What version of AdvancedReplay and ProtocolLib do you use?

**Comment by bobhenl** [comment]
> What version of AdvancedReplay and ProtocolLib do you use?

[16:40:15 INFO]: AdvancedReplay version 1.8.11
[16:40:15 INFO]: Author: Jumper251
version protocollib
[16:40:19 INFO]: ProtocolLib version 5.3.0
[16:40:19 INFO]: Provides read/write access to the Minecraft protocol.
[16:40:19 INFO]: Authors: dmulloy2 and comphenix

@Jumper251

**Comment by Jumper251** [comment]
1.8.11 is optimized for 1.21.3. You could try to temporarily downgrade to 1.8.10 or update the server to 1.21.3.
