### ISSUE TITLE
java.io.OptionalDataException when playing replay

### ISSUE THREAD

**Issue by Ziigur** [Jumper251/AdvancedReplay#30]
Hi,

We are getting this exception with some replays when playing them with `/replay play <name of the replay>`.

It starts to load the replay, but fails after telling the player "Loading replay...".

The server is running PaperSpigot 1.8.8 version and we are using the latest 1.6.4 version of the AdvancedReplay.

```
[19:52:53 WARN]: java.io.OptionalDataException
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1670)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
[19:52:53 WARN]:        at java.util.HashMap.readObject(HashMap.java:1410)
[19:52:53 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:52:53 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:52:53 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:52:53 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[19:52:53 WARN]:        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
[19:52:53 WARN]:        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
[19:52:53 WARN]:        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
[19:52:53 WARN]:        at me.jumper251.replay.filesystem.saving.DefaultReplaySaver$1.getValue(DefaultReplaySaver.java:77)
[19:52:53 WARN]:        at me.jumper251.replay.filesystem.saving.DefaultReplaySaver$1.getValue(DefaultReplaySaver.java:1)
[19:52:53 WARN]:        at me.jumper251.replay.utils.fetcher.Acceptor.run(Acceptor.java:17)
[19:52:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:52:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:52:53 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:52:53 WARN]: Exception in thread "pool-34-thread-2"
[19:52:53 WARN]: java.lang.NullPointerException
[19:52:53 WARN]:        at me.jumper251.replay.commands.replay.ReplayPlayCommand$1.accept(ReplayPlayCommand.java:43)
[19:52:53 WARN]:        at me.jumper251.replay.commands.replay.ReplayPlayCommand$1.accept(ReplayPlayCommand.java:1)
[19:52:53 WARN]:        at me.jumper251.replay.utils.fetcher.Acceptor.run(Acceptor.java:17)
[19:52:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:52:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:52:53 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

**Comment by Jumper251** [comment]
Is there anything I can do to reproduce this issue?
Are you using a modified version of the plugin?
