### ISSUE TITLE
NullPointerException when enabling MySQL Connection

### ISSUE THREAD

**Issue by jonas-koll** [Jumper251/AdvancedReplay#37]
Hi there,
every time I want to enable mysql Support in the config settings, there comes a NullPointerException :(

The mysql config data works correct but obviously there is an error in your MySQL part if I'm right 😞 
Maybe you can help me? 😄 

```[18:39:51 ERROR]: Error occurred while enabling AdvancedReplay v1.6.4 (Is it up to date?)
java.lang.NullPointerException
        at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:74) ~[?:?]
        at me.jumper251.replay.database.MySQLService.createReplayTable(MySQLService.java:26) ~[?:?]
        at me.jumper251.replay.filesystem.ConfigManager.loadData(ConfigManager.java:124) ~[?:?]
        at me.jumper251.replay.filesystem.ConfigManager.loadConfigs(ConfigManager.java:87) ~[?:?]
        at me.jumper251.replay.ReplaySystem.onEnable(ReplaySystem.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
       ```

**Comment by Jumper251** [comment]
Are there any other error messages on startup?
Make sure use_msql is enabled in the config.yml and you have set the correct credentials in the mysql.yml.
