### ISSUE TITLE
Plugin is incompatible with 1.8.8

### ISSUE THREAD

**Issue by C0mplexityProjects** [Jumper251/AdvancedReplay#38]
The plugin seems to require a later version of java (java 11?) however on legacy versions of Minecraft a lot of servers still run on Java 8 since that was the version of java for the time.

`[22:26:17 ERROR]: Could not load 'plugins/Replay.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/jumper251/replay/ReplaySystem has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.UnsupportedClassVersionError: me/jumper251/replay/ReplaySystem has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_292]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_292]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_292]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_292]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 6 more`

**Comment by Jumper251** [comment]
I released a new update that should fix the issue.
