### ISSUE TITLE
Error With Spectating Players a Different World

### ISSUE THREAD

**Issue by milkgaming** [Jumper251/AdvancedReplay#40]
> [23:04:38 ERROR]: Could not pass event PlayerTeleportEvent to AdvancedReplay v1.6.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:325) ~[server.jar:1_8_R3]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:1_8_R3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:1_8_R3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[server.jar:1_8_R3]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:570) ~[server.jar:1_8_R3]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:253) ~[server.jar:1_8_R3]
at me.jumper251.replay.listener.ReplayListener.onClick(ReplayListener.java:141) ~[?:?]
at sun.reflect.GeneratedMethodAccessor1188.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:323) ~[server.jar:1_8_R3]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:1_8_R3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:1_8_R3]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:569) ~[server.jar:1_8_R3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1958) ~[server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:17) ~[server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:1) ~[server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:34) ~[server.jar:1_8_R3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) [server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:907) [server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:819) [server.jar:1_8_R3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:720) [server.jar:1_8_R3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.IllegalArgumentException: receiver cannot be NULL.
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:751) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
at com.comphenix.packetwrapper.AbstractPacket.sendPacket(AbstractPacket.java:63) ~[?:?]
at me.jumper251.replay.replaysystem.utils.entities.PacketNPCOld.despawn(PacketNPCOld.java:143) ~[?:?]
at me.jumper251.replay.listener.ReplayListener.onTeleport(ReplayListener.java:177) ~[?:?]
at sun.reflect.GeneratedMethodAccessor1190.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:323) ~[server.jar:1_8_R3]
... 27 more

**Comment by Jumper251** [comment]
How can I reproduce this error?
