### ISSUE TITLE
Error with mysql

### ISSUE THREAD

**Issue by RobTech1** [Jumper251/AdvancedReplay#41]
When I enable MySQL I get this error:
[17:11:24 WARN]: org.apache.commons.lang.UnhandledException: Plugin AdvancedReplay v1.6.6 generated an exception while executing task 51
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:74)
at me.jumper251.replay.database.utils.AutoReconnector.run(AutoReconnector.java:24)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

Here is my MySQL file: 
host: localhost:3306
username: admin
database: replays
password: 
prefix: 'replay'

**Comment by Jumper251** [comment]
Are there any other error messages on startup?
Make sure use_msql is enabled in the config.yml and you have set the correct credentials in the mysql.yml.

**Comment by RobTech1** [comment]
Use Mysql is enabled and i have the right credentials. 

I Get this error:

[00:42:37] [Server thread/INFO]: [Replay] Unable to connect to database: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
[00:42:37] [Server thread/ERROR]: Error occurred while enabling AdvancedReplay v1.6.6 (Is it up to date?)
java.lang.NullPointerException
	at me.jumper251.replay.database.MySQLDatabase.update(MySQLDatabase.java:74) ~[?:?]
	at me.jumper251.replay.database.MySQLService.createReplayTable(MySQLService.java:30) ~[?:?]
	at me.jumper251.replay.filesystem.ConfigManager.loadData(ConfigManager.java:129) ~[?:?]
	at me.jumper251.replay.filesystem.ConfigManager.loadConfigs(ConfigManager.java:90) ~[?:?]
	at me.jumper251.replay.ReplaySystem.onEnable(ReplaySystem.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Jumper251** [comment]
Which MySQL version are you using?

**Comment by RobTech1** [comment]
8.0.26-0ubuntu0.20.04.2

**Comment by Jumper251** [comment]
This seems to be a problem with MySQL version 8, I will try to fix this in the next update.

**Comment by RobTech1** [comment]
OKey, nice

**Comment by RobTech1** [comment]
When will the next update come out?

**Comment by Jumper251** [comment]
Should be fixed now.
