### ISSUE TITLE
error whilst recording for a couple of minutes

### ISSUE THREAD

**Issue by iligalodin** [Jumper251/AdvancedReplay#5]
Hello, I've come acrost a couple of errors whilst recording for a bit.
the exeptions are always 71 and 22

this is one of the errors

```
[23:11:15] [Craft Scheduler Thread - 15/WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.4 generated an exception while executing task 71
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_211]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_211]
        at me.jumper251.replay.replaysystem.recording.Recorder$1.run(Recorder.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-03bd4b0-6984fc4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-03bd4b0-6984fc4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

and this is the other one 

```
[21:22:11] [Craft Scheduler Thread - 1/WARN]: [AdvancedReplay] Plugin AdvancedReplay v1.4 generated an exception while executing task 22
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_211]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_211]
        at me.jumper251.replay.replaysystem.recording.Recorder$1.run(Recorder.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-03bd4b0-6984fc4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-03bd4b0-6984fc4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

The server is running 
CraftBukkit version git-Spigot-03bd4b0-6984fc4 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

Plugins i am running on the server are: 
- LuckPerms, 
- WorldEdit, 
- CrisTreeCapitator, 
- BetterShulkerBoxes, 
- AdvancedReplay, 
- Multiverse-Core, 
- ProtocolLib, 
- Multiverse-Inventories

**Comment by Jumper251** [comment]
I am aware of this error message and I am trying to fix it.
If the message only appears a couple of times the plugin should still record everything properly.
