### ISSUE TITLE
com.mojang.authlib.exceptions.AuthenticationException: null

### ISSUE THREAD

**Issue by iBuseWinner** [Jumper251/AdvancedReplay#58]
I think it's yours.

[12:21:00 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6088f981[id=8bf5674b-ce06-30b7-8171-9c2842105e06,name=MHF_ArrowRight,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: null
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:118) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:98) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:193) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[patched_1.17.1.jar:git-Purpur-1428]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$2(SkullBlockEntity.java:157) ~[app:?]
        at net.minecraft.Util.ifElse(Util.java:397) ~[app:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$5(SkullBlockEntity.java:154) ~[app:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jumper251** [comment]
I don't think AdvancedReplay is causing this, it looks like the server is unable to load the skin data of a skull item.
