### ISSUE TITLE
Recording error in 1.18.1

### ISSUE THREAD

**Issue by MrF1yn** [Jumper251/AdvancedReplay#65]
[17:11:36 ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
        at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]
        at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor366.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1541) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1386) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1445]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jumper251** [comment]
Looks similar to this issue #64

**Comment by MrF1yn** [comment]
Thanks
