### ISSUE TITLE
Could not pass event PlayerMoveEvent to AdvancedReplay v1.8 Error

### ISSUE THREAD

**Issue by FlyGuyGo** [Jumper251/AdvancedReplay#72]
I received this error when attempting to use AdvancedReplay with Vulcan Replay. I am on the latest AdvancedReplay, ProtocolLib and VulcanReplay. 

```
[00:45:47 ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
        at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]
        at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor170.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-134]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1496) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-134]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-134]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by FlyGuyGo** [comment]
It turns out that when starting a replay I receive this initial error followed by the one posted here
```
[01:17:55] [Server thread/WARN]: [AdvancedReplay] Task #54077 for AdvancedReplay v1.8 generated an exception
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.reflect.accessors.MethodAccessor.invoke(Object, Object[])" because "com.comphenix.protocol.wrappers.WrappedDataWatcher.SETTER" is null
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:510) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:404) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:411) ~[ProtocolLib.jar:?]
	at me.jumper251.replay.replaysystem.utils.MetadataBuilder.setValue(MetadataBuilder.java:30) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.utils.MetadataBuilder.setArrows(MetadataBuilder.java:58) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.spawnNPC(ReplayingUtils.java:448) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:85) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:145) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.replaying.Replayer.start(Replayer.java:99) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:69) ~[Replay.jar:?]
	at me.jumper251.replay.replaysystem.Replay.lambda$0(Replay.java:60) ~[Replay.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Jumper251** [comment]
You have to use the latest dev build for 1.18.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by FlyGuyGo** [comment]
> You have to use the latest ProtocolLib dev build for 1.18.
> https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Thank you for your help!
