### ISSUE TITLE
Carrot Error

### ISSUE THREAD

**Issue by FlyGuyGo** [Jumper251/AdvancedReplay#73]
A replay of someone planting carrots causes this error, which prevents the planted carrots from being seen.
```
[19:21:16] [Server thread/WARN]: [AdvancedReplay] Task #564684 for AdvancedReplay v1.8 generated an exception
java.lang.IllegalArgumentException: Cannot get data for not block CARROT
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData.newData(CraftBlockData.java:513) ~[paper-1.18.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2518) ~[paper-1.18.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2493) ~[paper-1.18.1.jar:git-Paper-136]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1925) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.Material.createBlockData(Material.java:4101) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setType(CraftBlock.java:171) ~[paper-1.18.1.jar:git-Paper-136]
	at me.jumper251.replay.replaysystem.replaying.ReplayingUtils$2.run(ReplayingUtils.java:521) ~[Replay.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Jumper251** [comment]
Should be fixed now.
