### ISSUE TITLE
PlayerInfo packet crash

### ISSUE THREAD

**Issue by TheGreatRambler** [Jumper251/AdvancedReplay#74]
When playing a replay, this cryptic error appears:

```
[13:02:07 WARN]: [AdvancedReplay] Task #9418 for AdvancedReplay v1.7 generated an exception
java.lang.IllegalAccessError: class com.comphenix.protocol.wrappers.PlayerInfoData$1 tried to access protected field com.comphenix.protocol.wrappers.AbstractWrapper.handle (com.comphenix.protocol.wrappers.PlayerInfoData$1 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @61ebda3b; com.comphenix.protocol.wrappers.AbstractWrapper is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7815e515)
        at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:121) ~[?:?]
        at com.comphenix.protocol.wrappers.PlayerInfoData$1.getGeneric(PlayerInfoData.java:96) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:300) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.setData(WrapperPlayServerPlayerInfo.java:53) ~[?:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.getInfoAddPacket(PacketNPC.java:296) ~[?:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.spawn(PacketNPC.java:101) ~[?:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.spawnNPC(ReplayingUtils.java:524) ~[?:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:95) ~[?:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:155) ~[?:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.start(Replayer.java:99) ~[?:?]
        at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:69) ~[?:?]
        at me.jumper251.replay.replaysystem.Replay.lambda$play$0(Replay.java:60) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

A version of this plugin 2 commits back doesn't have this issue and it doesn't seem you've touched any of these files. It's an identical error to https://www.spigotmc.org/threads/protocollib-playerinfo-packet-plugin-crash-illegalaccesserror.487746/. I'm compiling with ProtocolLib 1.7.0 and using the most recent snapshot 1.18 jar. (edit I meant 4.7.0)

**Comment by Jumper251** [comment]
You have to use the latest ProtocolLib dev build for 1.18.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by TheGreatRambler** [comment]
Do you have to use the latest ProtocolLib for compiling as well?

**Comment by Jumper251** [comment]
no compiling should be fine with 4.7.0
Is the spigot version of the plugin working?
Did you install any other plugins that could cause problems?

**Comment by TheGreatRambler** [comment]
My fork is modified in a lot of different files but I did manage to fix it by changing this line in ReplayingUtils
```
if (VersionUtil.isAbove(VersionEnum.V1_14) && Bukkit.getPlayer(action.getName()) != null) {
```
To
```
if (VersionUtil.isAbove(VersionEnum.V1_17) && Bukkit.getPlayer(action.getName()) != null) {
```
It appears it used to be V1_17 but you changed it in one of your most recent commits. Reverting that change fixed the issue in my fork.

**Comment by TheGreatRambler** [comment]
I should note I test primarily in 1.16 as that's the version I plan on using the most
