### ISSUE TITLE
big error with paper 1.18.1

### ISSUE THREAD

**Issue by HeresJohnny320** [Jumper251/AdvancedReplay#76]
[22:18:56 ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
	at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]
	at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor148.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-164]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1496) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:19:04 INFO]: HeresJohnny320 lost connection: Disconnected
[22:19:04 ERROR]: Could not pass event PlayerQuitEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitRunnable.cancel()" because "this.run" is null
	at me.jumper251.replay.replaysystem.replaying.Replayer.stop(Replayer.java:180) ~[Replay.jar:?]
	at me.jumper251.replay.listener.ReplayListener.onQuit(ReplayListener.java:189) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-164]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:610) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:595) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1990) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1970) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:714) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

[22:18:47 ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1496) ~[?:?]

	

	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-164]	at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]

			at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]

		at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-164]	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:42) ~[?:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor148.execute(Unknown Source) ~[?:?]

		at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-164]				at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-164][22:18:47 ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
	at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]
	at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor148.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-164]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1496) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jumper251** [comment]
You have to use the latest ProtocolLib dev build for 1.18.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by HeresJohnny320** [comment]
cool it works now but i found a small bug when you replay then stop the replay and the player dies and u stop the replay it will give you what they dropped so its duping the items

**Comment by HeresJohnny320** [comment]
https://youtu.be/obHhtdBL124 here is a vid i made showing it and u can see at the end what i mean and u can pick up thos

**Comment by Jumper251** [comment]
Do you only get this bug when using forward/backward or is the problem also there if you watch it without skipping?

**Comment by HeresJohnny320** [comment]
sorry for the late responds i kinda forgot to look back at github for a while but anyways ya that but even if i dont fast forward it will start duping and droping the items and everything so unless there is a way to see the inventory of the player but not have it drop when they die or something idk

**Comment by HeresJohnny320** [comment]
if you would like the replay file i can upload it for ya if that helps at all

**Comment by Jumper251** [comment]
Yes the replay file would help.

**Comment by Jumper251** [comment]
I also need the name of the world from the replay.

**Comment by HeresJohnny320** [comment]
![image](https://user-images.githubusercontent.com/34362911/156459873-5118a634-d876-49fb-9c6e-9facaa204748.png)
[MidwestGaming92-raid.zip](https://github.com/Jumper251/AdvancedReplay/files/8173330/MidwestGaming92-raid.zip) lol i could send the world but the world is 30gb so that would take me a while with 20 mb upload xD but here is the replay file and world name the world name is just the default world name

**Comment by Jumper251** [comment]
I cannot load the replay, did you reformat the file?
