### ISSUE TITLE
/record leave broken

### ISSUE THREAD

**Issue by Impactic48** [Jumper251/AdvancedReplay#81]
Server Info: 1.18.1 Purpur 1547

Plugins: https://gyazo.com/b09aec81b00cf2673819b0e262b01ac7 
(I'm using AntiCheatReplay which hooks into AdvancedReplay but there's no mention of that in the error)

So when I started up a recording and when I went to leave with the door and /record leave and now I'm unable to do anything with my account on my main server without restarting, I can't build, get blocks or items from the creative menu, can't break blocks, etc.

**This is the error message:**

[18:50:03] [Server thread/INFO]: Impactic issued server command: /replay leave
[18:50:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'replay' in plugin AdvancedReplay v1.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2187) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2168) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1490) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitRunnable.cancel()" because "this.run" is null
	at me.jumper251.replay.replaysystem.replaying.Replayer.stop(Replayer.java:180) ~[Replay.jar:?]
	at me.jumper251.replay.commands.replay.ReplayLeaveCommand.execute(ReplayLeaveCommand.java:29) ~[Replay.jar:?]
	at me.jumper251.replay.commands.AbstractCommand.onCommand(AbstractCommand.java:73) ~[Replay.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more

AND

[18:50:40] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AdvancedReplay v1.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "loc1" is null
	at me.jumper251.replay.replaysystem.replaying.ReplayHelper.isInRange(ReplayHelper.java:119) ~[Replay.jar:?]
	at me.jumper251.replay.listener.ReplayListener.onMove(ReplayListener.java:233) ~[Replay.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1547]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1562) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jumper251** [comment]
You have to use the latest ProtocolLib dev build for 1.18.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
