### ISSUE TITLE
Error when attempting to play Replays on 1.18.2

### ISSUE THREAD

**Issue by EvanMcGregor** [Jumper251/AdvancedReplay#91]
Hello, I am using Paper 1.18.2, ver 299. 

I am using ProtocolLib Dev 5.0, but the latest standard release gives the same error.

When I try to play replays, I get the following error:

```
[21:39:46 INFO]: EPThree issued server command: /replay play EPThree
[21:39:46 WARN]: [AdvancedReplay] Task #8 for AdvancedReplay v1.6.4 generated an exception
java.lang.IllegalArgumentException: No enum constant me.jumper251.replay.utils.VersionUtil.VersionEnum.V1_18
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.jumper251.replay.utils.VersionUtil$VersionEnum.valueOf(VersionUtil.java:1) ~[Replay.jar:?]
        at me.jumper251.replay.utils.VersionUtil.isAbove(VersionUtil.java:27) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayPacketListener.<init>(ReplayPacketListener.java:40) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplaySession.<init>(ReplaySession.java:42) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.<init>(Replayer.java:70) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:68) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.lambda$0(Replay.java:60) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-299]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-299]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-299]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-299]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

How could this be solved?

**Comment by Jumper251** [comment]
You have to use the latest version of AdvancedReplay (currently 1.8.1).
